# Generated by Django 3.2.23 on 2023-11-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210522_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Property', 'Property'), ('Furniture', 'Furniture'), ('Mobiles', 'Mobiles'), ('Bikes', 'Bikes'), ('Books&Sports', 'Books&Sports'), ('Fashion', 'Fashion'), ('Cars', 'Cars'), ('Electronics', 'Electronics'), ('Jobs', 'Jobs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('HP', 'Haryana'), ('TS', 'Telegana'), ('JH', 'Jharkhand'), ('NL', 'Nagaland'), ('UK', 'Uttarakhand'), ('CG', 'Chhattisgarh'), ('BR', 'Bihar'), ('GJ', 'Gujarat'), ('KA', 'Karnataka'), ('TN', 'Tamil Nadu'), ('AP', 'Andhra Pradesh'), ('MN', 'Manipur'), ('MH', 'Maharashtra'), ('PB', 'Punjab'), ('OD', 'Odisha'), ('GA', 'Goa'), ('TR', 'Tripura'), ('MZ', 'Mizoram'), ('AR', 'Arunachal Pradesh'), ('MI', 'Sikkim'), ('RJ', 'Rajasthan'), ('ML', 'Meghalaya'), ('AS', 'Assam'), ('MP', 'Madhya Pradesh'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('KL', 'Kerala')], max_length=100),
        ),
    ]
