# Generated by Django 3.2.23 on 2023-11-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20231117_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Bikes', 'Bikes'), ('Property', 'Property'), ('Books&Sports', 'Books&Sports'), ('Jobs', 'Jobs'), ('Fashion', 'Fashion'), ('Mobiles', 'Mobiles'), ('Furniture', 'Furniture'), ('Cars', 'Cars')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('BR', 'Bihar'), ('MP', 'Madhya Pradesh'), ('AP', 'Andhra Pradesh'), ('TS', 'Telegana'), ('NL', 'Nagaland'), ('HP', 'Haryana'), ('TN', 'Tamil Nadu'), ('UK', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('AS', 'Assam'), ('CG', 'Chhattisgarh'), ('PB', 'Punjab'), ('KA', 'Karnataka'), ('GJ', 'Gujarat'), ('TR', 'Tripura'), ('OD', 'Odisha'), ('WB', 'West Bengal'), ('KL', 'Kerala'), ('MN', 'Manipur'), ('JH', 'Jharkhand'), ('RJ', 'Rajasthan'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('MI', 'Sikkim'), ('GA', 'Goa'), ('AR', 'Arunachal Pradesh'), ('MH', 'Maharashtra')], max_length=100),
        ),
    ]
