# Generated by Django 4.2.7 on 2023-11-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20231118_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Bikes', 'Bikes'), ('Electronics', 'Electronics'), ('Books&Sports', 'Books&Sports'), ('Property', 'Property'), ('Furniture', 'Furniture'), ('Fashion', 'Fashion'), ('Jobs', 'Jobs'), ('Cars', 'Cars'), ('Mobiles', 'Mobiles')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('ML', 'Meghalaya'), ('MN', 'Manipur'), ('MH', 'Maharashtra'), ('MP', 'Madhya Pradesh'), ('HP', 'Haryana'), ('UK', 'Uttarakhand'), ('RJ', 'Rajasthan'), ('KL', 'Kerala'), ('CG', 'Chhattisgarh'), ('KA', 'Karnataka'), ('AR', 'Arunachal Pradesh'), ('MI', 'Sikkim'), ('UP', 'Uttar Pradesh'), ('GA', 'Goa'), ('TN', 'Tamil Nadu'), ('JH', 'Jharkhand'), ('BR', 'Bihar'), ('PB', 'Punjab'), ('WB', 'West Bengal'), ('TR', 'Tripura'), ('GJ', 'Gujarat'), ('OD', 'Odisha'), ('AP', 'Andhra Pradesh'), ('TS', 'Telegana'), ('MZ', 'Mizoram'), ('AS', 'Assam'), ('NL', 'Nagaland')], max_length=100),
        ),
    ]
