# Generated by Django 4.2.7 on 2023-11-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='listing',
            name='hostel',
            field=models.CharField(choices=[('VI', 'Vindhya Hostel'), ('KC', 'Kalpana Chawla Hostel'), ('HI', 'Himalya Hostel'), ('SH', 'Shivalik Hostel'), ('AR', 'Aravali Hostel'), ('KR', 'Kurukshetra Hostel')], default='Kurukshetra Hostel', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='room',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='semester',
            field=models.CharField(choices=[('third', 'BTech 3rd'), ('eighth', 'BTech 8th'), ('fifth', 'BTech 5th'), ('tenth', 'MTech 2nd'), ('one', 'BTech 1st'), ('twelfth', 'MTech 4th'), ('eleventh', 'MTech 3rd'), ('thirteenth', 'PhD'), ('two', 'BTech 2nd'), ('seventh', 'BTech 7th'), ('sixth', 'BTech 6th'), ('fourth', 'BTech 4th'), ('ninth', 'MTech 1st')], default='BTech 1st', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electrical items', 'Electrical items'), ('Room Accessories', 'Room Accessories'), ('Bicycles', 'Bicycles'), ('Mobiles', 'Mobiles'), ('Sport Items', 'Sport Items'), ('Books', 'Books'), ('Fashion', 'Fashion'), ('General Accessories', 'General Accessories')],default='Books', max_length=100),
        ),
    ]
